Squashed commit of the following:
commit d4e5a7cdcc7d58097d1bdc8c547570a006668c40
Author: Masoud Moghani <moghani@cs.toronto.edu>
Date:   Thu Mar 13 09:34:55 2025 -0700

    Add ORBIT-Surgical (#23)

    Fixes
    [#22](https://github.com/isaac-for-healthcare/i4h-workflows/issues/22)

    This MR adds the ORBIT-Surgical project to the workflows -
    robotic_surgery.

commit 4b2eab2cbcb487a29b560bf722bdbceaf8ffbab1
Author: YunLiu <55491388+KumoLiu@users.noreply.github.com>
Date:   Thu Mar 13 13:31:56 2025 +0800

    Update default down direction in organ coord (#50)

    - use env.unwrapped.scene["organs"].data.root_pos_w directly to
    calculate the transform matrix instead of hard-code
    - update default down direction in organ coord from (-np.pi / 2, 0, 0)
    to (-np.pi / 2, -np.pi / 2, 0) since the probe is scan the Sagittal
    plane.
    - Use dataclass to define the down direction for the organ and mapping
    coordinate transforma matrix

    ---------

    Signed-off-by: YunLiu <55491388+KumoLiu@users.noreply.github.com>

commit d90c5bbcd38688d40fa280416833709c22f51190
Author: wendell-hom <60016436+wendell-hom@users.noreply.github.com>
Date:   Wed Mar 12 16:22:06 2025 -0700

    Add Clarius Cast and Clarius Solum Ultrasound Apps (#52)

    Adds two Holoscan SDK apps:
    * clarius_cast to stream ultrasound images from Clarius probe using Cast
    APIs
    * clarius_solum to stream ultrasound images from Clarius probe using
    Solum APIs

    ---------

    Co-authored-by: Wendell Hom <whom@nvidia.com>

commit 5fbd0f774de8f70ae9f87234601b6ce4962c0763
Author: Mingxin Zheng <18563433+mingxin-zheng@users.noreply.github.com>
Date:   Wed Mar 12 16:42:20 2025 +0800

    Update policy model ckpt path (#48)

    This PR changes the path for the model for the latest asset change.

    Related PR:
    https://github.com/isaac-for-healthcare/i4h-asset-catalog/pull/5

    ---------

    Signed-off-by: Mingxin Zheng <mingxinz@nvidia.com>

commit a8d83e6a04c43b73e0c646b44be16ca8e57c1667
Author: Yiheng Wang <68361391+yiheng-wang-nv@users.noreply.github.com>
Date:   Wed Mar 12 15:54:31 2025 +0800

    update convert hdf5 to lerobot script (#42)

    Fixes #ISSUE_NUMBER
    This PR updates the `convert_hdf5_to_lerobot.py` script to:
    1. Enhance Error Handling
    2. Improve Documentation
    3. Reduce Hardcoding
    4. Fix `test_training.py` error when the env has > 1 GPUs

    ---------

    Signed-off-by: Yiheng Wang <vennw@nvidia.com>
    Co-authored-by: Mingxin Zheng <18563433+mingxin-zheng@users.noreply.github.com>

commit 2cc4be7b3d9b2244e341cca81f4e7db4c75829dd
Author: YunLiu <55491388+KumoLiu@users.noreply.github.com>
Date:   Wed Mar 12 14:33:06 2025 +0800

    Integrate us raytracing simulator (#37)

    Integrate us raytracing simulator

    ---------

    Signed-off-by: YunLiu <55491388+KumoLiu@users.noreply.github.com>

commit 084061ea7020316993f83ab78d266d423a4b8253
Author: Nigel Nelson <61555377+NigelNelson@users.noreply.github.com>
Date:   Tue Mar 11 23:16:01 2025 -0700

    Add State Machine + Data Collection (#44)

    This MR adds the state machine which emulates a liver scan trajectory.
    It includes the ability to collect these scans as training episodes for
    IL policies by using the `.hdf5` format.

    Please see the state machine
    [README.md](https://github.com/isaac-for-healthcare/i4h-workflows/blob/f3a5ce5f5bfa4baf4fadf67bc0af6fc95a877bb9/workflows/robotic_ultrasound/scripts/simulation/README.md#liver-scan-state-machine)
    for more comprehensive information.

    Credit to @maximilianofir for the included updates that got the state
    machine working with the latest USD files

    ---------

    Signed-off-by: Nigel Nelson <nigeln@nvidia.com>
    Signed-off-by: Nigel Nelson <61555377+NigelNelson@users.noreply.github.com>
    Signed-off-by: Mingxin Zheng <mingxinz@nvidia.com>
    Co-authored-by: Mingxin Zheng <mingxinz@nvidia.com>

commit f95ef5f59e01f9ec2dbe3464264137617795a69c
Author: Nigel Nelson <61555377+NigelNelson@users.noreply.github.com>
Date:   Tue Mar 11 21:24:19 2025 -0700

    Fix policy runner (#46)

    This MR:

    - Sets env flag when running the policy so that it doesn't use all
    available GPU memory
    - Updates the starting pose of the robot
    - Updates the torso and camera positioning

    Please use the new model
    [here](https://drive.google.com/file/d/1BoZRCtQp7tlNik-enJqWgon-4yvf-m_R/view?usp=sharing)

    Then run with:
    ```bash
    python run_policy.py --rti_license_file <your RTI path>/rti_license.dat --ckpt_path <your model path>/pi0_sim_liver_scan --repo_id i4h/sim_liver_scan
    ```

    ---------

    Signed-off-by: Nigel Nelson <nigeln@nvidia.com>
    Co-authored-by: Mingxin Zheng <18563433+mingxin-zheng@users.noreply.github.com>

commit edf9200f833f0f19b6cc9657c9e7a68bddff544d
Author: Yiheng Wang <68361391+yiheng-wang-nv@users.noreply.github.com>
Date:   Wed Mar 12 12:07:41 2025 +0800

    Fix openpi issues (#43)

    Fixes #ISSUE_NUMBER

    When install `openpi`, some import dependencies lines are commented out.
    However, we should revert them back to avoid errors. For example, run
    `i4h-workflows/workflows/robotic_ultrasound/tests/test_training/test_training.py`
    will see errors like below:

    ```
    File "/localhome/local-vennw/code/i4h-workflows/openpi/src/openpi/shared/download.py", line 244, in _get_s3_transfer_manager
        transfer_config = s3_transfer.TransferConfig(
    NameError: name 's3_transfer' is not defined
    ```

    This PR fixes the issue.

    ---------

    Signed-off-by: Yiheng Wang <vennw@nvidia.com>
    Signed-off-by: Mingxin Zheng <mingxinz@nvidia.com>
    Co-authored-by: Mingxin Zheng <18563433+mingxin-zheng@users.noreply.github.com>
    Co-authored-by: Mingxin Zheng <mingxinz@nvidia.com>

commit 27d50a94a18d5beabd712d6fc11fcf4bc117c68a
Author: Mingxin Zheng <18563433+mingxin-zheng@users.noreply.github.com>
Date:   Wed Mar 12 10:46:41 2025 +0800

    Download I4H assets  (#28)

    This PR adds methods to download assets

    ---------

    Signed-off-by: Mingxin Zheng <mingxinz@nvidia.com>

commit 1292aa0b376990ba1561845d5de54532b770eb42
Author: wendell-hom <60016436+wendell-hom@users.noreply.github.com>
Date:   Tue Mar 11 18:30:44 2025 -0700

    Add realsense holoscan app (#41)

    Add realsense camera under holoscan_apps

    ---------

    Co-authored-by: Wendell Hom <whom@nvidia.com>